server:
  port: 9010
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrej-oss/config-server
          clone-on-start: true
          default-label: main
