server:
  port: 9003
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: gatawey-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - names: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallBack
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - names: CircuitBreaker
              args:
                name: department-service
                fallbackuri: forward:/departrmentServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: hysrtix.stream
